# Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
$AppIds = @(
    # 'CoreyButler.NVMforWindows'
    # 'dbeaver.dbeaver'
    # 'Docker.DockerDesktop'
    # 'GIMP.GIMP'
    # 'Git.Git'
    # 'Google.JapaneseIME'
    # 'JGraph.Draw'
    # 'Microsoft.VCRedist.2015+.x64'
    # 'RedHat.Podman'
    # 'RedHat.Podman-Desktop'
    # 'SlackTechnologies.Slack'
    # 'TortoiseGit.TortoiseGit'
    # 'TortoiseSVN.TortoiseSVN'
    '7zip.7zip'
    'Adobe.Acrobat.Reader.64-bit'
    'Bitwarden.Bitwarden'
    'bmatzelle.Gow'
    'Brave.Brave'
    'CubeSoft.CubePDF'
    'CubeSoft.CubePDFUtility'
    'DevToys-app.DevToys'
    'BellSoft.LibericaJDK.8.Full'
    'BellSoft.LibericaJDK.11.Full'
    'BellSoft.LibericaJDK.17.Full'
    'BellSoft.LibericaJDK.21.Full'
    'Flow-Launcher.Flow-Launcher'
    'Google.Chrome'
    'Graphviz.Graphviz'
    'JetBrains.Toolbox'
    'Meld.Meld'
    'Microsoft.PCManager.CN'
    'Microsoft.PowerShell'
    'Microsoft.PowerToys'
    'Microsoft.VisualStudioCode'
    'Microsoft.WindowsTerminal'
    'MilosParipovic.OneCommander'
    'Mozilla.Firefox'
    'Notepad++.Notepad++'
    'Oracle.VirtualBox'
    'qBittorrent.qBittorrent'
    'stnkl.EverythingToolbar'
    'TrackerSoftware.PDF-XChangeViewer'
    'Vivaldi.Vivaldi'
    'voidtools.Everything'
    'Volta.Volta'
    'WinMerge.WinMerge'
    'Xmind.Xmind.8'
)
$AppIds | ForEach-Object {
    & winget install --id $_ --silent --accept-package-agreements --accept-source-agreements
}
